name: Vulnerability analysis

on:
  workflow_run:
    workflows: [PR handler]
    types:
      - completed

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: pr-handler.yml
      - name: 'Set version'
        id: results
        run: |
          echo "::set-output name=VERSION::$(cat version/version)"
      - name: Snyk staff
        run: echo '{}' > deps.json
      - name: Upload dependency graph to Datadog
        uses: datadog/github-action-vulnerability-analysis@v0.3.2
        with:
          service: app-service
          version: ${{ steps.results.outputs.VERSION }}
          site: http://localhost
        env:
          DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
          DATADOG_APP_KEY: ${{ secrets.DATADOG_APP_KEY }}
